### PR TITLE
Fixed project cards alignment. Close #100

### LINKED ISSUE #100: Cards in a row being centered when there are less than 3 cards in the row

### PR DESCRIPTION
**Pull request by aaron2212**

### CODE REVIEW

File: src/components/app/project-gallery/panel.tsx [hunk 1]
```diff
@@ -12,7 +12,7 @@ interface PanelProps {
 const Wrapper = styled.div`
   display: flex;
   flex-wrap: wrap;
-  justify-content: center;
+  justify-content: flex-start;
```
Comment (roymoran) [inline src/components/app/project-gallery/panel.tsx]: were you able to view the behavior of this change on both mobile and desktop?
